v:0.3.1_rc (Stable) Full Test-Task Implementation.
Moving to OOP: Refactoring & code improvement:
+ added 'testEndFailure' method

TC9:
* improved STDOUT tracking
* - #TODO:#BUG: same problem happens here -- "Please verify you are a human" page - undefined method `text' for nil:NilClass (NoMethodError) --- SOLVED (testEndFailure)

TC10: -- Refactoring 60%
- #TODO:#BUG: same problem happens here -- "Please verify you are a human" page - undefined method `text' for nil:NilClass (NoMethodError) --- removed
- #TODO: Make a proper checking, as defined in task!!! -- solved & removed
* Improved checking method (like in TC7), made it common.

TC11: -- Refactoring 80%
 * improved STDOUT tracking

!WARN:
Freelancer Class:
+ #TODO: Make general output method for Freelancer object. (like obj.toString())
+ Bug was detected! (#TODO: BUG-Cases: -- was added)

!NOTE:
+ Refactoring status was updated:
...
* TC9  #Status: - fixed bug
* TC10 #Status: Refactoring [60%]
* TC11 #Status: Refactoring [80%]
...